// <auto-generated />
using System;
using EFDAL.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFDAL.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFDAL.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("category_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("category_name")
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id")
                        .HasName("ProductCategoriesPK");

                    b.ToTable("EF_ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Телефоны и аксессуары"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Компьютеры и оргтехника"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Электроника"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Бытовая техника"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Автотовары"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Одежда для мужчин"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Спорт и развлечения"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Для дома и сада"
                        });
                });

            modelBuilder.Entity("EFDAL.Models.Product", b =>
                {
                    b.Property<string>("GTIN")
                        .HasColumnName("product_gtin")
                        .HasColumnType("varchar(14)");

                    b.Property<int?>("CategoryId")
                        .HasColumnName("category_id");

                    b.Property<string>("Description")
                        .HasColumnName("product_description")
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("product_name")
                        .HasColumnType("varchar(250)");

                    b.Property<decimal?>("Price")
                        .HasColumnName("product_price")
                        .HasColumnType("money");

                    b.Property<int?>("VendorId")
                        .HasColumnName("vendor_id");

                    b.HasKey("GTIN")
                        .HasName("ProductsPK");

                    b.HasIndex("CategoryId");

                    b.HasIndex("VendorId");

                    b.ToTable("EF_Products");

                    b.HasData(
                        new
                        {
                            GTIN = "00032662684547",
                            CategoryId = 3,
                            Description = "Liitokala 100% оригинал INR18650 30Q батарея 3000 мАч литиевая батарея inr18650 Питание аккумуляторная батарея электрические инструменты",
                            Name = "Liitokala 100% оригинал INR18650",
                            Price = 15.39m,
                            VendorId = 8
                        },
                        new
                        {
                            GTIN = "00032758904354",
                            CategoryId = 7,
                            Description = "Ammoon AP-09 педаль для гитары Looper Nano Серия Петля электрогитарная педаль эффектов настоящий обход неограниченное количество гитарных деталей",
                            Name = "Ammoon AP-09 педаль для гитары",
                            Price = 32.90m,
                            VendorId = 7
                        },
                        new
                        {
                            GTIN = "00032904589723",
                            CategoryId = 4,
                            Description = "Умный робот-пылесос Xiaomi SKV4022GL для сухой уборки, белый",
                            Name = "Робот-пылесос Xiaomi SKV4022GL",
                            Price = 254.89m,
                            VendorId = 1
                        },
                        new
                        {
                            GTIN = "00032908549186",
                            CategoryId = 6,
                            Description = "Космический корабль Timeline футболка вдохновлен Доктор Кто Звездные войны Звезда Забавный Бесплатная доставка Harajuku Модные топы Классический уникальный",
                            Name = "Футболка вдохновлен Доктор Кто",
                            Price = 12.64m,
                            VendorId = 9
                        },
                        new
                        {
                            GTIN = "00032917974724",
                            CategoryId = 4,
                            Description = "ANIMORE отпариватель для одежды бытовая техника Вертикальный Отпариватель с паровой железной щеткой утюг для глажки одежды для дома 110-220 В",
                            Name = "ANIMORE отпариватель для одежды",
                            Price = 22.00m,
                            VendorId = 11
                        },
                        new
                        {
                            GTIN = "00032967492017",
                            CategoryId = 1,
                            Description = "Оригинальные xiaomi mi note 3 чехол для xiaomi note3 задняя крышка Силиконовая окантовкка тканевый чехол подлинный xiaomi брендовая Мягкая прочная оболочка",
                            Name = "Оригинальные xiaomi mi note 3 ",
                            Price = 4.99m,
                            VendorId = 1
                        },
                        new
                        {
                            GTIN = "00032977895029",
                            CategoryId = 1,
                            Description = "Смартфон Xiaomi Redmi Note 7 с глобальной версией, 4 ГБ, 64 ГБ, Восьмиядерный процессор Snapdragon 660, 4000 мАч, 2340x1080, 48мп, двойная камера, мобильный телефон",
                            Name = "Смартфон Xiaomi Redmi Note 7",
                            Price = 210.99m,
                            VendorId = 1
                        },
                        new
                        {
                            GTIN = "00032984767921",
                            CategoryId = 3,
                            Description = "SanDisk A1 карты памяти 200 GB 128 GB 64 GB 98 МБ/с. 32 GB Micro sd Card Class10 UHS-1 флэш-карты памяти Microsd TF/sd карты s для планшета карта памяти флешка",
                            Name = "SanDisk A1 карты памяти 200 GB",
                            Price = 71.99m,
                            VendorId = 6
                        },
                        new
                        {
                            GTIN = "00032988897730",
                            CategoryId = 6,
                            Description = "Вентилятор воин Самурай японский семь добродетелей Bushido Новинка 2019 года короткий рукав для мужчин модные круглый средства ухода за кожей Шеи х",
                            Name = "Футболка 'Самурай'",
                            Price = 14.71m,
                            VendorId = 10
                        },
                        new
                        {
                            GTIN = "00033025568455",
                            CategoryId = 1,
                            Description = "Смартфон Xiaomi Redmi K20 Pro с глобальной прошивкой, 6 ГБ, 64 ГБ, Восьмиядерный процессор Snapdragon 855 4000 мАч, всплывающая фронтальная камера 48мп, AMOLED 6,39'",
                            Name = "Смартфон Xiaomi Redmi K20 Pro",
                            Price = 331.99m,
                            VendorId = 1
                        },
                        new
                        {
                            GTIN = "00033031000740",
                            CategoryId = 5,
                            Description = "CBR650R CB650R 2019 Новый Мото кластер Защита от царапин пленка приборная панель Крышка ЗАЩИТА ТПУ Blu-Ray для HONDA CBR650R",
                            Name = "ЗАЩИТА ТПУ Blu-Ray для HONDA CBR650R",
                            Price = 8.37m,
                            VendorId = 5
                        },
                        new
                        {
                            GTIN = "00033035890038",
                            CategoryId = 4,
                            Description = "Xiaomi 3 life Новый мини воздушный Циркуляционный Вентилятор 180 градусов вращение 330 сильный ветер мощность Usb зарядка низкий уровень шума высокий ветер",
                            Name = "Xiaomi 3 life Новый мини воздушный Циркуляционный Вентилятор",
                            Price = 12.99m,
                            VendorId = 1
                        },
                        new
                        {
                            GTIN = "00033046647870",
                            CategoryId = 1,
                            Description = "Новый оригинальный аккумулятор 2500 мАч для телефона INOI 2 Lite INOI2 Lite замена батареи высокого качества + номер отслеживания",
                            Name = "Аккумулятор 2500 мАч для телефона INOI 2 Lite INOI2 Lite",
                            Price = 10.18m,
                            VendorId = 4
                        },
                        new
                        {
                            GTIN = "00033051637203",
                            CategoryId = 3,
                            Description = "Мини Портативный микшер с USB DJ микшерная консоль MP3 Jack 4 канала караоке 48 V усилитель для караоке ktv матч Вечерние",
                            Name = "Мини Портативный микшер с USB",
                            Price = 10.18m,
                            VendorId = 7
                        },
                        new
                        {
                            GTIN = "00033059439610",
                            CategoryId = 2,
                            Description = "Капа для Samsung Galaxy Tab A 10,1 чехол, Премиум PU кожаный чехол-подставка Tab A6 10,1' 2016 планшет SM-T580/T585 авто сна/Пробуждение чехол",
                            Name = "Капа для Samsung Galaxy Tab A 10",
                            Price = 10.18m,
                            VendorId = 2
                        },
                        new
                        {
                            GTIN = "04000002194089",
                            CategoryId = 2,
                            Description = "Ноутбук Dell Inspiron 5370 (Intel Core i5-8250U/4 GB ram/128G SSD/13,3 ''FHD) Ноутбук Dell-brande",
                            Name = "Ноутбук Dell Inspiron 5370",
                            Price = 10.18m,
                            VendorId = 3
                        });
                });

            modelBuilder.Entity("EFDAL.Models.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("vendor_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnName("vendor_address")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("vendor_name")
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id")
                        .HasName("VendorsPK");

                    b.ToTable("EF_Vendors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "ShenZhen City, Guangdong, China",
                            Name = "Mi Global Store"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Guangdong China",
                            Name = "ZAIR Official Vendor"
                        },
                        new
                        {
                            Id = 3,
                            Address = "China",
                            Name = "MAOSHUANG Store"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Guangdong China",
                            Name = "AsusISonyIHuaweiIMeizuIXiaomiOfficialVendor"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Guangdong China",
                            Name = "SpeedmotoVendor"
                        },
                        new
                        {
                            Id = 6,
                            Address = "China",
                            Name = "SanDiskSD"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Guangdong China",
                            Name = "Ammoon Official"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Shenzhen, Guangdong, China",
                            Name = "LiitoKala Official Flagship"
                        },
                        new
                        {
                            Id = 9,
                            Address = "China",
                            Name = "Animelover"
                        },
                        new
                        {
                            Id = 10,
                            Address = "China",
                            Name = "The Dark Knight"
                        },
                        new
                        {
                            Id = 11,
                            Address = "China",
                            Name = "ANIMORE Official Vendor"
                        });
                });

            modelBuilder.Entity("EFDAL.Models.Product", b =>
                {
                    b.HasOne("EFDAL.Models.Category", "CategoryNav")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EFDAL.Models.Vendor", "VendorNav")
                        .WithMany("Products")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
